### ISSUE TITLE
Is this effective?

### ISSUE THREAD

**Issue by andrews05** [Helias/PNG-reindexing#2]
Hi, I've been researching PNG palette sorting techniques and came across your project here. Can I ask what your conclusions from this are? I tried running it on the included sample image and a couple of others but the output compressed worse than a typical luminance sort.

**Comment by Helias** [comment]
Hi, sure, sometimes it was better, sometimes the same or worse than the standard pypng compression.

comparison between [8x8 images](https://drive.google.com/file/d/1_iR8OOtKTnDUJgr5qLhBIWDo5GoNvIW8/view?usp=sharing):
<img width="443" alt="image" src="https://github.com/Helias/PNG-reindexing/assets/519778/d36d5a6f-be55-4be6-8192-32903546626a">

Experiments with the dataset Synthetic:
<img width="513" alt="image" src="https://github.com/Helias/PNG-reindexing/assets/519778/2ef7c90d-f327-497a-9e42-7f0bc7a2f3df">

Download link of images before and after https://drive.google.com/file/d/1XHc8SigFOeuPbM53M9hfuK7b4qmuja-j/view?usp=sharing

Hope this was helpful, if you need anything do not hesitate to comment, otherwise, close the issue ;-)

**Comment by andrews05** [comment]
Awesome, thank you!
